### ISSUE TITLE
Provide list of names for ACDC sets?

### ISSUE THREAD

**Issue by Karol-G** [BWGZK/CycleMix#6]
Hey,

I would like to make some experiments on the ACDC dataset with scribbles and would like to use the same train, val and test set as you to be comparable. I believe you further divided the train set into a sub train set 1 (35 cases) and a sub train set 2 (35 cases)?
Could you provide the list of names used for every set and sub set?

Thanks a lot in advance!

Best,
Karol

**Comment by BWGZK** [comment]
Sorry for the late reply. I have uploaded the ACDC dataset via https://github.com/BWGZK/ModelMix/tree/main/ACDC_dataset. We randomly select the sub train set. I believe you can achieve similar performance by randomly select it.
